version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: central_postgres
    environment:
      POSTGRES_DB: centraldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: central_rabbitmq
    ports:
      - "5672:5672"   # Puerto de comunicación AMQP
      - "15672:15672" # Panel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
